[package]
name = "vibes_comp_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
convert_case = "0.6.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
